import mongoose, { Document, Schema } from "mongoose";

/**
 * Canonical, scraped/grounded tournament record.
 * One row per real tournament — NOT regenerated by the pathway LLM call.
 * Populated/refreshed only by the scraper (RealDataScraperService).
 */
export interface TournamentDocument extends Document {
  sportSlug: string;
  name: string;
  level: string;
  description: string;
  ageGroup: string;
  prerequisiteId?: string;
  prerequisiteName?: string;
  prerequisiteGuide?: string[];
  documentChecklist?: string[];
  /** Real URLs returned by Google Search grounding — shown to parents as proof */
  sourceUrls: string[];
  /** false until an admin/moderator has eyeballed it */
  isVerified: boolean;
  lastScrapedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

const tournamentSchema = new Schema<TournamentDocument>(
  {
    sportSlug: { type: String, required: true, lowercase: true, index: true },
    name: { type: String, required: true, trim: true },
    level: { type: String, required: true },
    description: { type: String, required: true },
    ageGroup: { type: String, required: true },
    prerequisiteId: { type: String },
    prerequisiteName: { type: String },
    prerequisiteGuide: [{ type: String }],
    documentChecklist: [{ type: String }],
    sourceUrls: { type: [String], default: [] },
    isVerified: { type: Boolean, default: false },
    lastScrapedAt: { type: Date, default: Date.now },
  },
  { timestamps: true },
);

// Same tournament re-scraped for the same sport updates in place instead of duplicating.
tournamentSchema.index({ sportSlug: 1, name: 1 }, { unique: true });

export const Tournament =
  mongoose.models.Tournament ||
  mongoose.model<TournamentDocument>("Tournament", tournamentSchema);
